version: "3"

services:

  db:
    container_name: "metabase-postgres"
    image: postgres
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data/
      - ./services/postgres/:/docker-entrypoint-initdb.d/
    ports:
      - 54320:5432
    networks:
      - net

  app:
    container_name: "metabase-app"
    image: metabase/metabase
    env_file: .env
    ports:
      - 3000:3000
    networks:
      - net
    depends_on:
      - db

volumes:
  postgres-data:

networks:
  net:
