version: "3"

services:

  postgres:
    container_name: "data-engine_postgres"
    image: postgres
    env_file: .env
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
      - ./services/postgres/:/docker-entrypoint-initdb.d/
    ports:
      - 54320:5432

  metabase:
    container_name: "data-engine_metabase"
    image: metabase/metabase
    env_file: .env
    ports:
      - 3000:3000

volumes:
  postgres_volume:
